### PR TITLE
Return with an unknown error if a local socket exists on UNIX

### LINKED ISSUE #761: crashes when socket creation fails (`/tmp/avogadro` is an existing directory)
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 86c4e4f438b3d77ad1ef87081c595782dba0098d
 - Qt: 6.10.2

**Desktop version: (please complete the following information):**
 - OS: EndeavourOS
 - Compiler: GCC 15.2.1

**Describe the bug**
On a linux machine, socket is created as `/tmp/avogadro`.
https://github.com/OpenChemistry/avogadroapp/blob/140923f41ed9cc3dd2af1cd9fd37cee77444cbd5/avogadro/rpclistener.cpp#L34-L35

If `/tmp/avogadro` is an existing directory, avogadro crashes.

**To Reproduce**

```sh
mkdir /tmp/avogadro &&
avogadro2
```

Then a bunch of
```
Error starting RPC server: "QLocalServer::listen: Address in use"
Starting new server.
```
is printed and avogadro crashes with segmentation fault (infinite loop?).

**Expected behavior**

No segmentation fault occurs.

### PR DESCRIPTION
**Pull request by ghutchis**
Fix #761

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

## Summary by CodeRabbit

* **Bug Fixes**
  * Updated OpenGL requirement notification from version 2.0 to 4.0.
  * Improved error handling for socket connections on Unix systems.

### CODE REVIEW

File: avogadro/rpc/localsocketconnectionlistener.cpp [hunk 1]
```diff
@@ -36,6 +38,24 @@ LocalSocketConnectionListener::~LocalSocketConnectionListener()
...
+#if defined(Q_OS_UNIX)
+  // On Unix, QLocalServer creates a socket file in /tmp. If that path already
+  // exists but is not a socket (e.g. someone created /tmp/avogadro as a
+  // directory), listen() will fail with AddressInUseError. That would trigger
+  // the ping-and-retry logic, which tries to connect to a directory and
+  // crashes. Detect this case early and emit UnknownError so we skip the ping
+  // path.
+  QString socketPath = QDir::tempPath() + QLatin1Char('/') + m_connectionString;
+  QFileInfo fi(socketPath);
+  if (fi.exists() && !fi.isSocket()) {
```
Comment (e-kwsm) [inline avogadro/rpc/localsocketconnectionlistener.cpp]: Thank you for your work. Indeed the following patch fixes the issue

```suggestion
  if (fi.exists() && !fi.isOther()) {
```

but requires Qt 6.10 unfortunately.

https://doc.qt.io/qt-6/qfileinfo.html#isOther

**Review by e-kwsm — APPROVED** [review]
